/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xmlParser;
import xmlParser.implementations.DistanceCalculatorImpl;
import crosby.binary.osmosis.OsmosisReader;
import org.opengis.referencing.FactoryException;
import xmlParser.implementations.MyWay;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

public class XMLParser {
    private List<MyWay> ways = new ArrayList<>();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new XMLParser().getGreeting());
    }

    public void runReader(String path) throws FileNotFoundException {
        InputStream inputStream = new FileInputStream("C:/proj/BachelorProject/mapData/denmark-latest.osm.pbf");
        OsmosisReader reader = new OsmosisReader(inputStream);
        try {
            DistanceCalculatorImpl distCalc = new DistanceCalculatorImpl("EPSG:4326", "EPSG:25832");
            reader.setSink(new FirstPassSink(distCalc, this));
            reader.run();
        } catch (FactoryException e) {
            e.printStackTrace();
        }
    }

    public List<MyWay> getWays() {
        return ways;
    }
}
