/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XMLParser;
import XMLParser.Implementations.DistanceCalculatorImpl;
import crosby.binary.osmosis.OsmosisReader;
import org.opengis.referencing.FactoryException;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

public class XMLParser {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new XMLParser().getGreeting());
    }

    public void runReader(String path) throws FileNotFoundException {
        InputStream inputStream = new FileInputStream("C:/proj/BachelorProject/mapData/denmark-latest.osm.pbf");
        OsmosisReader reader = new OsmosisReader(inputStream);
        try {
            DistanceCalculatorImpl distCalc = new DistanceCalculatorImpl("EPSG:4326", "EPSG:25832");
            reader.setSink(new FirstPassSink(distCalc));
            reader.run();
        } catch (FactoryException e) {
            e.printStackTrace();
        }
    }
}
