/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XMLParser;


public class XMLParser {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new XMLParser().getGreeting());
    }
}
