/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XMLParser;
import crosby.binary.osmosis.OsmosisReader;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

public class XMLParser {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new XMLParser().getGreeting());
    }

    public void runReader(String path) throws FileNotFoundException {
        InputStream inputStream = new FileInputStream("C:/Users/svend/OneDrive/Uni/6. semester/Bachelor Project/denmark-latest.osm.pbf");
        OsmosisReader reader = new OsmosisReader(inputStream);
        reader.setSink(new MyOsmReader());
        reader.run();
    }
}
