/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xmlParser;

import org.junit.Before;
import org.junit.Test;
import xmlParser.implementations.MyWay;
import xmlParser.implementations.XMLParser;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class XMLParserTest {
    private XMLParser parser;

    @Before
    public void setUp() {
        parser = new XMLParser();
        try {
            parser.runReader("s");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }


    @Test
    public void checkForExistanceOfTwoKnownWays(){
            long id1 = 0;
            long id2 = 0;
            for(MyWay myWay: parser.getWays()) {
                long id = myWay.getId();
                if(id == 279060626){
                    id1 = id;
                }
                if(id == 616476468){
                    id2 = id;
                }
            }
            assertEquals(279060626, id1);
            assertEquals(616476468, id2);
    }

    @Test
    public void checkIfNumberOfNodesInDatastructureIsCorrect(){
        System.out.println(parser.getNodes().size());
        System.out.println(parser.getNodesToSearchFor().size());
        assertEquals(parser.getNodes().size(), parser.getNodesToSearchFor().size());
    }

}
