/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XMLParser;

import org.junit.Test;
import static org.junit.Assert.*;

public class XMLParserTest {
    @Test public void testAppHasAGreeting() {
        XMLParser classUnderTest = new XMLParser();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
