/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XMLParser;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class XMLParserTest {
    private XMLParser parser;

    @Before
    public void setUp() {parser = new XMLParser();}

    @Test
    public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", parser.getGreeting());
    }

}
