/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xmlParser.implementations;
import crosby.binary.osmosis.OsmosisReader;
import org.opengis.referencing.FactoryException;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.*;

public class XMLParser {
    private List<MyWay> ways = new ArrayList<>();
    private Set<Long> nodesToSearchFor = new HashSet<>();
    private Map<Long, MyNode> nodes = new HashMap<>();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new XMLParser().getGreeting());
    }

    public void runReader(String path) throws FileNotFoundException {
        InputStream inputStream = new FileInputStream("E:/Proj/BachelorProject/mapData/denmark-latest.osm.pbf");
        OsmosisReader reader = new OsmosisReader(inputStream);
        try {
            DistanceCalculatorImpl distCalc = new DistanceCalculatorImpl("EPSG:4326", "EPSG:25832");
            //First pass through data
            reader.setSink(new FirstPassSink(distCalc, this));
            reader.run();
            //Second pass through data
            InputStream inputStream1 = new FileInputStream("E:/Proj/BachelorProject/mapData/denmark-latest.osm.pbf");
            OsmosisReader reader1 = new OsmosisReader(inputStream1);
            reader1.setSink(new SecondPassSink(this));
            reader1.run();
        } catch (FactoryException e) {
            e.printStackTrace();
        }
    }

    public List<MyWay> getWays() {
        return ways;
    }

    public Set<Long> getNodesToSearchFor() {
        return nodesToSearchFor;
    }

    public Map<Long, MyNode> getNodes() {
        return nodes;
    }

}
